# Generated by Django 3.2.12 on 2022-03-28 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220326_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 30, 15, 38, 33, 270837, tzinfo=utc), null=True),
        ),
    ]
