# Generated by Django 3.2.12 on 2022-03-31 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220329_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 2, 18, 42, 31, 77266, tzinfo=utc), null=True),
        ),
    ]
